spring.application.name=SmartRent_Backend
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/smartrent
spring.datasource.username=postgres
spring.datasource.password=1010